public enum AuthorizationRequestFieldConstants: String {
    case clientId = "client_id"
    case clientIdScheme = "client_id_scheme"
    case responseType = "response_type"
    case responseMode = "response_mode"
    case presentationDefinition = "presentation_definition"
    case presentationDefinitionUri = "presentation_definition_uri"
    case responseUri = "response_uri"
    case redirectUri = "redirect_uri"
    case requestUri = "request_uri"
    case requestUriMode = "request_uri_mode"
    case nonce = "nonce"
    case state = "state"
    case clientMetadata = "client_metadata"
}
